### ISSUE TITLE
 GET https://cdn.rawgit.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by PN1019** [pointhi/leaflet-color-markers#11]
Got this error when I added the code to my dbHelper.js 
![2018-10-08 23_19_35-_e__users_abhishek_downloads_mws-restaurant-stage-1_js_dbhelper js - notepad](https://user-images.githubusercontent.com/16081831/46625218-b1772d80-cb50-11e8-8f62-aba9989c81a8.png)
Initially, I thought it is Chrome Bug followed the guidelines from this https://support.symantec.com/en_US/article.TECH240507.html   to set up the registry for it but didn't work. 
![2018-10-08 23_24_07-restaurant reviews](https://user-images.githubusercontent.com/16081831/46625363-54c84280-cb51-11e8-826a-c07444fe2c32.png)
I tried opening the site in the website in Incognito mode to know if any extension is hindering the execution but that's also not the case.
See the above map instead of markers it looking like this??

Please help me out how to solve this???

**Comment by PN1019** [comment]
@pointhi  please help here !!!

**Comment by pointhi** [comment]
No idea why the image are not found. Try to use the network view of your browser to find out what happen

**Comment by PN1019** [comment]
@pointhi  figured out the solution as I am working on PWA app I need to add images locally.
