### ISSUE TITLE
Svg sources

### ISSUE THREAD

**Issue by ThomasKientz** [pointhi/leaflet-color-markers#13]
Would be awesome to open source the vector sources (.svg, .ai) as well !

**Comment by pointhi** [comment]
there are simply no vector sources. They are derivatives of the official marker present in leaflet with some color shifting.

**Comment by NicoHood** [comment]
Could you maybe explain, how you did the change? I'd like to have a marker with a special RGB color and would like to know how to reproduce this. Thanks :-)
