### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jamespole** [pointhi/leaflet-color-markers#5]
Under which license have you released your images and JavaScript files?

**Comment by pointhi** [comment]
The blue marker is the same as from the original Leaflet source, and the other ones are colour altered (derivations) of this base marker made by me.
Simply speaking, my intend was to release the images under the same licence as the original one. Either BSD-2, or any other licence under which the original image were released (Often graphics has other licences than the source).

The js was added in #2. From a legal perspective, we should clarify the licence with the author.

**Comment by patrickp-rthinfo** [comment]
Thanks for sharing this repo @pointhi. I found it useful today. By convention, I'd encourage you to add a LICENSE file to the root directory, so it becomes obvious under which open license the contents are available.

**Comment by Micromegass** [comment]
So just to be clear... Can I use these icons from a legal perspective or is this problematic? Privately and on a company page?

**Comment by NicoHood** [comment]
@pointhi can you please add a license file?

**Comment by patrickp-rthinfo** [comment]
provided the proposal as pull request.

**Comment by NicoHood** [comment]
Nice! Would you mind tagging a new release then?

**Comment by heptalium** [comment]
> The js was added in #2. From a legal perspective, we should clarify the licence with the author.

As author of pull request #2 I release my contribution also under the BSD 2-Clause License.
