### ISSUE TITLE
Missing shadow img

### ISSUE THREAD

**Issue by ghost** [pointhi/leaflet-color-markers#6]
in image folder is missing:
'img/marker-shadow.png',

**Comment by TomZastrow** [comment]
I was running into the same problem: from the JS definitions, delete the lines

shadowUrl: 'img/marker-shadow.png',
shadowSize: [41, 41]

**Comment by RDCH106** [comment]
The problem was fixed in this PR: https://github.com/pointhi/leaflet-color-markers/pulls
I am waiting for the @pointhi merge.

@SucheG @TomZastrow you can use my fork with the fix: https://github.com/RDCH106/leaflet-color-markers

**Comment by pointhi** [comment]
Fixed in https://github.com/pointhi/leaflet-color-markers/pull/8
