### ISSUE TITLE
Install via Bower

### ISSUE THREAD

**Issue by demiankatz** [pointhi/leaflet-color-markers#9]
I'm trying to better manage my project's dependencies, and in support of that, it would be nice to be able to load this via Bower. I would be willing to put together a pull request with a bower.json if that would be helpful -- just let me know, as I don't want to spend the time before I know that you will be interested in merging it.

Thanks!

**Comment by pointhi** [comment]
I would merge it with pleasure, even though I don't know bower ^^. Just create the PR.

**Comment by demiankatz** [comment]
Thanks, @pointhi, I've just opened #10 to address this. There are some other steps you'll need to take to finish the process, which I have described on the PR. Let me know if I can be of further assistance!

**Comment by demiankatz** [comment]
(Also note that I took the liberty of setting the license in the bower.json to BSD as discussed on #5 -- feel free to adjust if that was not the best option).
